### ISSUE TITLE
Blank Target record opening when working on existing Target

### ISSUE THREAD

**Issue by SholtoD** [WebCuratorTool/webcurator#46]
When working on a target record sometimes WCT generates a new blank record with the existing records name.

**Comment by obrienben** [comment]
Caused by wappalyzer browser plugin.
Wappalyzer is used to detect what kinds of technologies are used to implement websites. To detect the servers, Wappalyzer will request the robots.txt to evaluate which pages are allowed. The existing WCT session ID is not included inside the request. So the WCT WebApp will register this request as a new session, and redirect the user back to the login page. After that any temporary data bound to old sessions are cleared, i.e. editing a Target.
